name: Update MLB Runs Given Up

on:
  schedule:
    - cron: '0 7 * * *'  # This will run the workflow daily at 3:00am Eastern Time (UTC-4/UTC-5 depending on daylight saving)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pybaseball pandas

      - name: Generate HTML Page
        run: |
          python MLB_runs_given_up.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'andrewscheiner'
          git config --global user.email 'andrewscheinergithub@github.com'
          git add .
          git commit -m 'Update MLB Runs Given Up'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
